### ISSUE TITLE
LLC compilation for registered target llvmpic fails

### ISSUE THREAD

**Issue by indicatelovelace** [llvm-pic/llvm-pic#14]
lc --stop-after=gMIR test.c > test1
llc: /home/indicatelove/prog/llvmpic/llvm/tools/llc/llc.cpp:570: compileModule(char**, llvm::LLVMContext&)::<lambda(llvm::StringRef, llvm::StringRef)>: Assertion `Target && "Could not allocate target machine!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.

Fix Target Registration

**Comment by pr1metine** [comment]
Should be fixed by #32
