### ISSUE TITLE
Establish Calling Convention

### ISSUE THREAD

**Issue by pr1metine** [llvm-pic/llvm-pic#15]

**Comment by omarandlorraine** [comment]
From my point of view, the PICs seem a little like a 6502: very few registers, the stack is not that convenient, and it is awkward to compile C to.

Given that, the llvm-mos fork may have some insight into how to do a calling convention. From what I understand, they simply pass arguments in statically allocated memory locations for all functions that are not reentrant. Maybe there is some work there we can use for PIC as well.

**Comment by pr1metine** [comment]
Yep, we take lots of inspiration from llvm-mos. If you want to, feel free to join our discord https://discord.gg/zysbHnwMbQ

**Comment by pr1metine** [comment]
FYI, this is LLVM-MOS' calling convention:

https://llvm-mos.org/wiki/C_calling_convention
