### ISSUE TITLE
Working Target Registration

### ISSUE THREAD

**Issue by indicatelovelace** [llvm-pic/llvm-pic#18]

**Comment by pr1metine** [comment]
Currently experiencing the following compiler error:

```
error: unknown target triple 'picmid'
```

**Comment by pr1metine** [comment]
> ```
>error: unknown target triple 'picmid'
> ```
So I found out why our clang fork throws this error when trying to compile anything.

Consider the following command:
```
cd <path/to/your/llvm-pic/clone>
 "./llvm/build/bin/clang-17" -cc1 -triple picmid -emit-obj -mrelax-all -dumpdir a- -disable-free -clear-ast-before-backend -main-file-name main.bc -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -debugger-tuning=gdb -target-linker-version 1015.7 -v -fcoverage-compilation-dir=./llvm/build/bin -resource-dir ./llvm/build/lib/clang/17 -fdebug-compilation-dir=./llvm/build/bin -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -o /var/folders/d2/2l1bpj590md3q7p2m8gn7f8c0000gn/T/main-8a67cf.o -x ir ./llvm/lib/Target/PICMid/Examples/main.bc
```

When debugging it, you eventually get to the part where clang tries to create the appropriate target info for your desired triple, i.e., `picmid`: 

https://github.com/llvm-pic/llvm-pic/blob/b841c41bee6cbd6a313568ef8209c6bd47fd8ba0/clang/lib/Basic/Targets.cpp#L772-L778

Apparently, clang requires us to define separate, clang-specific target info about our `picmid` target:

https://github.com/llvm-pic/llvm-pic/blob/b841c41bee6cbd6a313568ef8209c6bd47fd8ba0/clang/lib/Basic/Targets.cpp#L112-L125

AFAIK, using clang at this stage is not necessary anyways as we only use it for debug purposes. I'd stick to `llc` as outlined in this [target registration guide](http://jonathan2251.github.io/lbd/llvmstructure.html#id98). Further work on creating the target info necessary to enable picmid support for clang may be tracked with #22.
