### ISSUE TITLE
Describe PIC16F883 microcontroller in Studienarbeit

### ISSUE THREAD

**Issue by pr1metine** [llvm-pic/llvm-pic#56]
**Is your feature request related to a problem? Please describe.**
LLVM-PIC is a student project called „Studienarbeit“. As part of it, we are required to author a paper also called „Studienarbeit“.

**Describe the solution you'd like**
This Studienarbeit primarily aims to produce machine code which may be executed on the PIC16F883 microcontroller. A chapter in it should detail this.

**Describe alternatives you've considered**
The Studienarbeit may merely brush over PIC16F883. Details can be attached to the Studienarbeit as an appendix.

**Additional context**
- [Studienarbeit draft](https://typst.app/project/rJ_jyzn2D4Mnostf5KgJmW)
- [PIC16F883 datasheet](https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/40001291H.pdf)

**Comment by indicatelovelace** [comment]
Chapter 3.1 now describes the most significant hardware architecture of the PIC that are relevant for a compiler, such as architecture, stack, accumulator, etc.

**Comment by indicatelovelace** [comment]
See above
