### ISSUE TITLE
Assertion failed: (TablesInitialized && "backend forgot to call computeTables")

### ISSUE THREAD

**Issue by handiener** [llvm-pic/llvm-pic#68]
**Describe the bug**
When wompiling a C file with a void main function only containing a variable declaration, the pipeline fails.

**To Reproduce**
```c
void main(void) {
    // int asdf = 1234;
}
```
```sh
clang void.c
```

**Expected behavior**
The invocation of the clang should produce an ELF file (a.out)

**Screenshots**
test-inputs/void.c:4:16: warning: implicit conversion from 'long' to 'int' changes value from 1234 to -46 [-Wconstant-conversion]
    4 |     int asdf = 1234;
      |         ~~~~   ^~~~
Assertion failed: (TablesInitialized && "backend forgot to call computeTables"), function getAspectAction, file LegacyLegalizerInfo.cpp, line 198.
lowerFormallowerReturnPLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/bin/clang-17 -cc1 -triple picmid -emit-obj -mrelax-all -dumpdir a- -disable-free -clear-ast-before-backend -main-file-name void.c -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -ffreestanding -std=c17 -mframe-pointer=none -debugger-tuning=gdb -target-linker-version 1053.12 -fcoverage-compilation-dir=/Users/hannes/Desktop/Studienarbeit/llvm-pic-experiments -resource-dir /Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/clang/17 -I/opt/homebrew/include/opencv4/ -I/opt/homebrew/include/opencv4/ -I. -cxx-isystem /opt/homebrew/include -cxx-isystem /opt/homebrew/include -cxx-isystem . -internal-isystem /Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/clang/17/include -fdebug-compilation-dir=/Users/hannes/Desktop/Studienarbeit/llvm-pic-experiments -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -o /var/folders/nf/sskb9mcn3vs15bbr3f8q2rx80000gn/T/void-b38e78.o -x c test-inputs/void.c
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'test-inputs/void.c'.
4.      Running pass 'Legalizer' on function '@main'
 #0 0x0000000111370f04 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMSupport.dylib+0x290f04)
 #1 0x00000001113714a0 PrintStackTraceSignalHandler(void*) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMSupport.dylib+0x2914a0)
 #2 0x000000011136f188 llvm::sys::RunSignalHandlers() (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMSupport.dylib+0x28f188)
 #3 0x00000001113726f0 SignalHandler(int) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMSupport.dylib+0x2926f0)
 #4 0x00000001966b3584 (/usr/lib/system/libsystem_platform.dylib+0x180477584)
 #5 0x0000000196682c20 (/usr/lib/system/libsystem_pthread.dylib+0x180446c20)
 #6 0x000000019658fa20 (/usr/lib/system/libsystem_c.dylib+0x180353a20)
 #7 0x000000019658ed10 (/usr/lib/system/libsystem_c.dylib+0x180352d10)
 #8 0x000000011222c3ac llvm::LegacyLegalizerInfo::getAspectAction(llvm::InstrAspect const&) const (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMGlobalISel.dylib+0x2303ac)
 #9 0x000000011222db30 llvm::LegacyLegalizerInfo::getAction(llvm::LegalityQuery const&) const (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMGlobalISel.dylib+0x231b30)
#10 0x0000000112223f88 llvm::LegalizerInfo::getAction(llvm::LegalityQuery const&) const (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMGlobalISel.dylib+0x227f88)
#11 0x000000011222423c llvm::LegalizerInfo::getAction(llvm::MachineInstr const&, llvm::MachineRegisterInfo const&) const (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMGlobalISel.dylib+0x22823c)
#12 0x00000001121d7f94 llvm::LegalizerHelper::legalizeInstrStep(llvm::MachineInstr&, llvm::LostDebugLocObserver&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMGlobalISel.dylib+0x1dbf94)
#13 0x00000001121c2f50 llvm::Legalizer::legalizeMachineFunction(llvm::MachineFunction&, llvm::LegalizerInfo const&, llvm::ArrayRef<llvm::GISelChangeObserver*>, llvm::LostDebugLocObserver&, llvm::MachineIRBuilder&, llvm::GISelKnownBits*) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMGlobalISel.dylib+0x1c6f50)
#14 0x00000001121c4a80 llvm::Legalizer::runOnMachineFunction(llvm::MachineFunction&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMGlobalISel.dylib+0x1c8a80)
#15 0x0000000109d93e04 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMCodeGen.dylib+0x543e04)
#16 0x000000011479686c llvm::FPPassManager::runOnFunction(llvm::Function&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMCore.dylib+0x3ae86c)
#17 0x000000011479dcf4 llvm::FPPassManager::runOnModule(llvm::Module&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMCore.dylib+0x3b5cf4)
#18 0x00000001147970f0 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMCore.dylib+0x3af0f0)
#19 0x0000000114796c74 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMCore.dylib+0x3aec74)
#20 0x000000011479e0fc llvm::legacy::PassManager::run(llvm::Module&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libLLVMCore.dylib+0x3b60fc)
#21 0x0000000105287dd4 (anonymous namespace)::EmitAssemblyHelper::RunCodegenPipeline(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>&, std::__1::unique_ptr<llvm::ToolOutputFile, std::__1::default_delete<llvm::ToolOutputFile>>&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangCodeGen.dylib+0x3fdd4)
#22 0x000000010526aca4 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangCodeGen.dylib+0x22ca4)
#23 0x0000000105269d7c clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangCodeGen.dylib+0x21d7c)
#24 0x0000000105bfddd0 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangCodeGen.dylib+0x9b5dd0)
#25 0x000000011a65e9a0 clang::ParseAST(clang::Sema&, bool, bool) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangParse.dylib+0x69a0)
#26 0x000000010c0901a8 clang::ASTFrontendAction::ExecuteAction() (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangFrontend.dylib+0x3241a8)
#27 0x0000000105bfbe34 clang::CodeGenAction::ExecuteAction() (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangCodeGen.dylib+0x9b3e34)
#28 0x000000010c08f970 clang::FrontendAction::Execute() (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangFrontend.dylib+0x323970)
#29 0x000000010bf8d9f0 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangFrontend.dylib+0x2219f0)
#30 0x00000001030daccc clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/lib/libclangFrontendTool.dylib+0x6ccc)
#31 0x00000001029c40f4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/bin/clang-17+0x10001c0f4)
#32 0x00000001029b27bc ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/bin/clang-17+0x10000a7bc)
#33 0x00000001029b14c8 clang_main(int, char**, llvm::ToolContext const&) (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/bin/clang-17+0x1000094c8)
#34 0x00000001029ebbb0 main (/Users/hannes/Desktop/Studienarbeit/llvm-pic/llvm/build/bin/clang-17+0x100043bb0)
#35 0x00000001962fa0e0 
clang: error: unable to execute command: Abort trap: 6
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 17.0.6 (https://github.com/llvm-pic/llvm-pic.git 799501a43e01df2471edc785429aefa73f932604)
Target: picmid
Thread model: posix
InstalledDir: /Users/hannes/Desktop/Studienarbeit/llvm-pic-experiments/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/nf/sskb9mcn3vs15bbr3f8q2rx80000gn/T/void-ccceee.c
clang: note: diagnostic msg: /var/folders/nf/sskb9mcn3vs15bbr3f8q2rx80000gn/T/void-ccceee.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/hannes/Library/Logs/DiagnosticReports/clang-17_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************

**Desktop (please complete the following information):**
 - OS: MacOS 
- Version 14.4.1

**Additional context**
test cases are not yet in the repo

https://github.com/llvm-pic/llvm-pic/commit/d12067206e6253d3ce53615f771432a8e75c825d

**Comment by pr1metine** [comment]
To fix the above issue, we need to call the following function in the `PICMidLegalizerInfo` constructor:

```cpp
getLegacyLegalizerInfo().computeTables();
```
